Repository ikjo93/share-travel, pull requests merged in 2023-05, with the labels that each got.

#3 [FE/Setting] Vue-Cli 기반 프로젝트 초기화
  fe/.browserslistrc
  fe/.eslintrc.js
  fe/.gitignore
  fe/babel.config.js
  fe/jest.config.js
  fe/jsconfig.json
  fe/package-lock.json
  fe/package.json
  fe/public/favicon.ico
  fe/public/index.html
  fe/src/App.vue
  fe/src/api/index.js
  fe/src/assets/logo.png
  fe/src/components/common/AppHeader.vue
  fe/src/css/common.css
  fe/src/main.js
  fe/src/routes/index.js
  fe/src/store/index.js
  fe/src/utils/cookies.js
  fe/src/views/MainPage.vue
  fe/tests/unit/example.spec.js
  fe/vue.config.js
Labels: 📜 setting

#5 [Fe/feature/main-view] 메인화면 주요 컴포넌트 개발
  fe/public/google_logo.png
  fe/public/kakao_logo.png
  fe/public/naver_logo.png
  fe/src/App.vue
  fe/src/components/common/AppFooter.vue
  fe/src/components/common/AppHeader.vue
  fe/src/components/main/AppGuide.vue
  fe/src/components/main/ImageSlider.vue
  fe/src/components/travel/ShareTravelMap.vue
  fe/src/main.js
  fe/src/routes/index.js
  fe/src/store/index.js
  fe/src/views/BoardPage.vue
  fe/src/views/LoginPage.vue
  fe/src/views/MainPage.vue
Labels: 👨‍💻 feature

#6 [Be/feature/auth] Spring Security 기반 OAuth2 및 JWT 인증/인가 기능 구현
  be/.gitignore
  be/build.gradle
  be/src/main/java/com/sharetravel/ServerApplication.java
  be/src/main/java/com/sharetravel/domain/user/controller/UserController.java
  be/src/main/java/com/sharetravel/domain/user/dto/UserResponseDto.java
  be/src/main/java/com/sharetravel/domain/user/dto/UserUpdateRequestDto.java
  be/src/main/java/com/sharetravel/domain/user/entity/Role.java
  be/src/main/java/com/sharetravel/domain/user/entity/User.java
  be/src/main/java/com/sharetravel/domain/user/repository/UserRepository.java
  be/src/main/java/com/sharetravel/domain/user/service/UserService.java
  be/src/main/java/com/sharetravel/global/ApiResponseCode.java
  be/src/main/java/com/sharetravel/global/ApiResponseMessage.java
  be/src/main/java/com/sharetravel/global/BaseTimeEntity.java
  be/src/main/java/com/sharetravel/global/CommonUtil.java
  be/src/main/java/com/sharetravel/global/ServletUtil.java
  be/src/main/java/com/sharetravel/global/auth/jwt/argumentresolver/RefreshTokenId.java
  be/src/main/java/com/sharetravel/global/auth/jwt/argumentresolver/RefreshTokenIdArgumentResolver.java
  be/src/main/java/com/sharetravel/global/auth/jwt/dto/AccessTokenResponse.java
  be/src/main/java/com/sharetravel/global/auth/jwt/dto/JwtAuthenticationResult.java
  be/src/main/java/com/sharetravel/global/auth/jwt/dto/LoginSuccessResponse.java
  be/src/main/java/com/sharetravel/global/auth/jwt/exception/HackedTokenException.java
  be/src/main/java/com/sharetravel/global/auth/jwt/exception/InvalidTokenException.java
  be/src/main/java/com/sharetravel/global/auth/jwt/filter/JwtAuthenticationFilter.java
  be/src/main/java/com/sharetravel/global/auth/jwt/handler/TokenHandler.java
  be/src/main/java/com/sharetravel/global/auth/jwt/repository/RefreshTokenRepository.java
  be/src/main/java/com/sharetravel/global/auth/jwt/service/AccessTokenService.java
  be/src/main/java/com/sharetravel/global/auth/jwt/service/RefreshTokenService.java
  be/src/main/java/com/sharetravel/global/auth/jwt/service/TokenService.java
  be/src/main/java/com/sharetravel/global/auth/oauth2/dto/CustomOAuth2User.java
  be/src/main/java/com/sharetravel/global/auth/oauth2/dto/GoogleOAuth2UserInfo.java
  be/src/main/java/com/sharetravel/global/auth/oauth2/dto/KakaoOAuth2UserInfo.java
  be/src/main/java/com/sharetravel/global/auth/oauth2/dto/NaverOAuth2UserInfo.java
  be/src/main/java/com/sharetravel/global/auth/oauth2/dto/OAuth2Provider.java
  be/src/main/java/com/sharetravel/global/auth/oauth2/dto/OAuth2UserInfo.java
  be/src/main/java/com/sharetravel/global/auth/oauth2/dto/OAuthAttributes.java
  be/src/main/java/com/sharetravel/global/auth/oauth2/exception/UnsupportedOAuth2ProviderException.java
  be/src/main/java/com/sharetravel/global/auth/oauth2/handler/CustomAuthenticationFailureHandler.java
  be/src/main/java/com/sharetravel/global/auth/oauth2/handler/CustomAuthenticationSuccessHandler.java
  be/src/main/java/com/sharetravel/global/auth/oauth2/service/CustomOAuth2UserService.java
  be/src/main/java/com/sharetravel/global/auth/oauth2/utils/OAuth2UserInfoUtil.java
  be/src/main/java/com/sharetravel/global/config/MvcConfig.java
  be/src/main/java/com/sharetravel/global/config/RedisConfig.java
  be/src/main/java/com/sharetravel/global/config/SecurityConfig.java
  be/src/main/resources/application.yml
Labels: 👨‍💻 feature

#9 [Infra] AWS 인프라 구축 및 스프링 부트 웹 앱 자동 배포 flow 구성
  .github/workflows/cicd-be.yml
  README.md
  be/Dockerfile
  be/src/main/resources/application.yml
Labels: 🖥 infra

#10 [Infra/hotfix] CI/CD 수동 테스트 위한 트리거 추가 설정
  .github/workflows/cicd-be.yml
  README.md
Labels: 🔧 hot fix

#12 [Infra] Github Actions workflow file 및 Dockerfile 오류분 수정
  .github/workflows/cicd-be.yml
  .github/workflows/manual-deploy-be.yml
  README.md
  be/Dockerfile
Labels: 🖥 infra

#13 [Infra] spring boot web app 불필요한 도커 이미지 생성 문제 개선
  .github/workflows/cicd-be.yml
  .github/workflows/manual-deploy-be.yml
Labels: 🖥 infra

#14 [Be/feature/auth] OAuth2 로그인 완료 시 클라이언트에 액세스 토큰 전달 방식 변경
  be/src/main/java/com/sharetravel/global/ApiResponseCode.java
  be/src/main/java/com/sharetravel/global/ServletUtil.java
  be/src/main/java/com/sharetravel/global/auth/jwt/handler/TokenHandler.java
  be/src/main/java/com/sharetravel/global/auth/oauth2/handler/CustomAuthenticationSuccessHandler.java
Labels: 👨‍💻 feature

#15 [Be/feature/auth] 액세스 토큰 전달 방식 롤백 처리
  be/src/main/java/com/sharetravel/global/ApiResponseCode.java
  be/src/main/java/com/sharetravel/global/ServletUtil.java
  be/src/main/java/com/sharetravel/global/auth/jwt/handler/TokenHandler.java
  be/src/main/java/com/sharetravel/global/auth/oauth2/handler/CustomAuthenticationSuccessHandler.java
Labels: 👨‍💻 feature

#17 [Be/hotfix/auth] Spring Security redirect uri 설정 오류분 수정
  be/src/main/resources/application.yml
Labels: 🔧 hot fix

#18 [Fe/feature/auth] 클라이언트 OAuth2 로그인 API 구현
  fe/src/api/auth.js
  fe/src/api/config/interceptors.js
  fe/src/api/index.js
  fe/src/api/user.js
  fe/src/assets/css/common.css
  fe/src/assets/css/reset.css
  fe/src/components/common/AppHeader.vue
  fe/src/routes/index.js
  fe/src/store/index.js
  fe/src/utils/cookies.js
  fe/src/views/OAuthLoginPage.vue
  fe/src/views/UserInputPage.vue
Labels: 👨‍💻 feature

#19 [Be/feature/auth] OAuth2 로그인 완료 시 사용자 전달 방식 개선
  be/src/main/java/com/sharetravel/global/ApiResponseCode.java
  be/src/main/java/com/sharetravel/global/ServletUtil.java
  be/src/main/java/com/sharetravel/global/auth/jwt/handler/TokenHandler.java
  be/src/main/java/com/sharetravel/global/auth/oauth2/handler/CustomAuthenticationSuccessHandler.java
  be/src/main/java/com/sharetravel/global/config/SecurityConfig.java
  be/src/main/resources/application.yml
Labels: 👨‍💻 feature

#20 [Be/hotfix/auth] 스프링 시큐리티 CORS 설정 등 커밋 누락분 긴급 수정
  be/src/main/java/com/sharetravel/global/auth/oauth2/handler/CustomAuthenticationSuccessHandler.java
  be/src/main/java/com/sharetravel/global/config/SecurityConfig.java
Labels: 🔧 hot fix

#21 [Fe/feature/board] 게시판 화면 프레임 및 주요 컴포넌트 개발
  fe/package-lock.json
  fe/public/fonts/ttf/BMHANNAPro.ttf
  fe/public/icon_noresult.png
  fe/public/light.png
  fe/src/App.vue
  fe/src/components/board/BoardJumbotron.vue
  fe/src/components/board/content/BoardDetail.vue
  fe/src/components/board/content/BoardEvent.vue
  fe/src/components/board/content/BoardGeneralForum.vue
  fe/src/components/board/content/BoardNotice.vue
  fe/src/components/board/content/BoardTipForum.vue
  fe/src/components/common/AppFooter.vue
  fe/src/components/common/AppHeader.vue
  fe/src/routes/index.js
  fe/src/views/BoardPage.vue
Labels: 👨‍💻 feature

#22 feat : 게시판 수정/삭제/검색창 화면 구현
  fe/public/search_icon.png
  fe/src/components/board/BoardJumbotron.vue
  fe/src/components/board/BoardWrite.vue
  fe/src/components/board/content/BoardDetail.vue
  fe/src/components/board/content/BoardGeneralForum.vue
  fe/src/components/board/content/BoardQna.vue
  fe/src/routes/index.js
Labels: 👨‍💻 feature

#24 [Fe/feature/auth] 페이지 새로고침 시 리프레쉬 토큰을 이용한 액세스 토큰 발급 로직 구현
  fe/src/App.vue
  fe/src/api/auth.js
  fe/src/api/config/interceptors.js
  fe/src/api/index.js
  fe/src/api/user.js
  fe/src/components/common/AppHeader.vue
  fe/src/routes/index.js
  fe/src/store/index.js
  fe/src/utils/cookies.js
  fe/src/views/OAuthLoginPage.vue
Labels: 👨‍💻 feature

#25 [Refactor/auth] 액세스 토큰 발급 관련 서버 및 클라이언트 로직 리팩토링
  be/src/main/java/com/sharetravel/domain/user/controller/UserController.java
  be/src/main/java/com/sharetravel/domain/user/entity/User.java
  be/src/main/java/com/sharetravel/global/api/ApiResponseCode.java
  be/src/main/java/com/sharetravel/global/api/ApiResponseMessage.java
  be/src/main/java/com/sharetravel/global/api/ApiUtil.java
  be/src/main/java/com/sharetravel/global/auth/jwt/controller/TokenController.java
  be/src/main/java/com/sharetravel/global/auth/jwt/filter/JwtAuthenticationFilter.java
  be/src/main/java/com/sharetravel/global/auth/oauth2/handler/CustomAuthenticationFailureHandler.java
  be/src/main/java/com/sharetravel/global/auth/oauth2/handler/CustomAuthenticationSuccessHandler.java
  be/src/main/java/com/sharetravel/global/config/SecurityConfig.java
  be/src/main/java/com/sharetravel/global/domain/BaseTimeEntity.java
  be/src/main/java/com/sharetravel/global/exception/GlobalExceptionHandler.java
  be/src/main/java/com/sharetravel/global/servlet/ServletUtil.java
  fe/src/App.vue
  fe/src/api/config/interceptors.js
  fe/src/api/index.js
  fe/src/store/index.js
  fe/vue.config.js
Labels: ♻ refactor

#26 [document] 프로젝트 관련 README 파일 수정
  README.md
Labels: 🧾 document

#30 [Feature/travel] 사용자 닉네임 및 여행지 키워드 입력 화면 및 기능 개발
  be/src/main/java/com/sharetravel/domain/travelkeyword/controller/TravelKeywordController.java
  be/src/main/java/com/sharetravel/domain/travelkeyword/dto/TravelKeywordResponseDto.java
  be/src/main/java/com/sharetravel/domain/travelkeyword/entity/TravelKeyword.java
  be/src/main/java/com/sharetravel/domain/travelkeyword/repository/TravelKeywordRepository.java
  be/src/main/java/com/sharetravel/domain/travelkeyword/service/TravelKeywordService.java
  be/src/main/java/com/sharetravel/domain/user/controller/UserController.java
  be/src/main/java/com/sharetravel/domain/user/dto/UserInfoRegisterForm.java
  be/src/main/java/com/sharetravel/domain/user/dto/UserInfoUpdateRequestDto.java
  be/src/main/java/com/sharetravel/domain/user/dto/UserResponseDto.java
  be/src/main/java/com/sharetravel/domain/user/dto/UserUpdateRequestDto.java
  be/src/main/java/com/sharetravel/domain/user/entity/Role.java
  be/src/main/java/com/sharetravel/domain/user/entity/User.java
  be/src/main/java/com/sharetravel/domain/user/entity/UserTravelKeyword.java
  be/src/main/java/com/sharetravel/domain/user/repository/UserRepository.java
  be/src/main/java/com/sharetravel/domain/user/service/UserService.java
  be/src/main/java/com/sharetravel/global/api/ApiResponseCode.java
  be/src/main/java/com/sharetravel/global/auth/jwt/filter/JwtAuthenticationFilter.java
  be/src/main/java/com/sharetravel/global/auth/oauth2/dto/OAuthAttributes.java
  be/src/main/resources/application.yml
  be/src/main/resources/data.sql
  be/src/main/resources/schema.sql
  fe/src/App.vue
  fe/src/api/index.js
  fe/src/api/travel.js
  fe/src/api/user.js
  fe/src/components/common/AppHeader.vue
  fe/src/components/common/LoadingSpinner.vue
  fe/src/components/user/LoginModal.vue
  fe/src/components/user/UserInputModal.vue
  fe/src/routes/index.js
  fe/src/store/index.js
  fe/src/views/UserInputPage.vue
Labels: 👨‍💻 feature, 👨‍💻 backend, 👨‍💻 frontend

#34 [Feature/user] 사용자 회원탈퇴 및 로그아웃 기능 구현
  be/build.gradle
  be/src/main/java/com/sharetravel/domain/travelkeyword/exception/NotFoundTravelKeywordException.java
  be/src/main/java/com/sharetravel/domain/user/controller/UserController.java
  be/src/main/java/com/sharetravel/domain/user/entity/User.java
  be/src/main/java/com/sharetravel/domain/user/exception/InvalidMailAuthorizationCodeException.java
  be/src/main/java/com/sharetravel/domain/user/repository/MailAuthorizationCodeRepository.java
  be/src/main/java/com/sharetravel/domain/user/service/UserService.java
  be/src/main/java/com/sharetravel/global/api/ApiResponseCode.java
  be/src/main/java/com/sharetravel/global/auth/jwt/controller/TokenController.java
  be/src/main/java/com/sharetravel/global/auth/jwt/filter/JwtAuthenticationFilter.java
  be/src/main/java/com/sharetravel/global/auth/jwt/service/RefreshTokenService.java
  be/src/main/java/com/sharetravel/global/auth/jwt/utils/TokenUtils.java
  be/src/main/java/com/sharetravel/global/auth/oauth2/service/CustomOAuth2UserService.java
  be/src/main/java/com/sharetravel/global/config/RedisInitializer.java
  be/src/main/resources/application.yml
  fe/src/App.vue
  fe/src/api/auth.js
  fe/src/api/index.js
  fe/src/api/user.js
  fe/src/components/common/AppHeader.vue
  fe/src/components/user/UserInputModal.vue
  fe/src/components/user/mypage/UserNavigation.vue
  fe/src/components/user/mypage/UserUpdateModal.vue
  fe/src/routes/index.js
Labels: 👨‍💻 feature, 👨‍💻 backend, 👨‍💻 frontend

#35 [Feature/auth] axios retry 를 통한 Access token 재발급 및 재요청 구현
  be/.gitignore
  be/src/main/resources/application.yml
  fe/src/App.vue
  fe/src/api/config/interceptors.js
Labels: 👨‍💻 feature, 👨‍💻 frontend

#37 [Feature/board] 게시판 API 부분 구현
  be/.gitignore
  be/src/main/java/com/sharetravel/domain/board/controller/BoardController.java
  be/src/main/java/com/sharetravel/domain/board/dto/BoardDto.java
  be/src/main/java/com/sharetravel/domain/board/entity/Board.java
  be/src/main/java/com/sharetravel/domain/board/repository/BoardRepository.java
  be/src/main/java/com/sharetravel/domain/board/service/BoardService.java
  be/src/main/java/com/sharetravel/domain/boardCategory/controller/BoardCategoryController.java
  be/src/main/java/com/sharetravel/domain/boardCategory/dto/BoardCategoryDto.java
  be/src/main/java/com/sharetravel/domain/boardCategory/entity/BoardCategory.java
  be/src/main/java/com/sharetravel/domain/boardCategory/repository/BoardCategoryRepository.java
  be/src/main/java/com/sharetravel/domain/boardCategory/sevice/BoardCategoryService.java
  be/src/main/java/com/sharetravel/global/api/ApiResponseCode.java
  be/src/main/resources/schema.sql
  fe/src/api/board.js
  fe/src/api/index.js
  fe/src/components/board/BoardJumbotron.vue
  fe/src/components/board/content/BoardEvent.vue
  fe/src/components/board/content/BoardGeneralForum.vue
  fe/src/components/board/content/BoardNotice.vue
  fe/src/components/board/content/BoardQna.vue
  fe/src/components/board/content/BoardTipForum.vue
Labels: 👨‍💻 feature, 👨‍💻 backend, 👨‍💻 frontend

#39 [Feature/travel] 여행지 정보 등록 기능 구현
  .github/workflows/cicd-be.yml
  .github/workflows/manual-deploy-be.yml
  be/build.gradle
  be/src/main/java/com/sharetravel/domain/image/entity/Image.java
  be/src/main/java/com/sharetravel/domain/image/exception/ImageUploadException.java
  be/src/main/java/com/sharetravel/domain/image/repository/ImageRepository.java
  be/src/main/java/com/sharetravel/domain/image/service/ImageService.java
  be/src/main/java/com/sharetravel/domain/travel/controller/TravelController.java
  be/src/main/java/com/sharetravel/domain/travel/dto/TravelRequestDto.java
  be/src/main/java/com/sharetravel/domain/travel/dto/TravelResponseDto.java
  be/src/main/java/com/sharetravel/domain/travel/entity/Travel.java
  be/src/main/java/com/sharetravel/domain/travel/repository/TravelRepository.java
  be/src/main/java/com/sharetravel/domain/travel/service/TravelService.java
  be/src/main/java/com/sharetravel/domain/travelkeyword/entity/TravelKeyword.java
  be/src/main/java/com/sharetravel/domain/travelreview/entity/TravelReview.java
  be/src/main/java/com/sharetravel/domain/user/entity/User.java
  be/src/main/java/com/sharetravel/domain/user/entity/UserTravelKeyword.java
  be/src/main/java/com/sharetravel/domain/user/service/UserService.java
  be/src/main/java/com/sharetravel/global/api/ApiResponseCode.java
  be/src/main/java/com/sharetravel/global/config/AWSConfig.java
  be/src/main/java/com/sharetravel/global/exception/GlobalExceptionHandler.java
  be/src/main/resources/application.yml
  be/src/main/resources/schema.sql
  fe/src/App.vue
  fe/src/api/index.js
  fe/src/api/travel.js
  fe/src/components/common/AppFooter.vue
  fe/src/components/travel/ShareTravelMap.vue
  fe/src/components/travel/TravelSearchBar.vue
  fe/src/views/ShareTravelPage.vue
Labels: 👨‍💻 feature, 👨‍💻 backend, 👨‍💻 frontend

#40 [Feature/travel] 여행지 정보 등록 기능 개선 및 조회 기능 구현
  be/build.gradle
  be/src/main/java/com/sharetravel/domain/image/repository/ImageRepository.java
  be/src/main/java/com/sharetravel/domain/travel/controller/TravelController.java
  be/src/main/java/com/sharetravel/domain/travel/dto/TravelRequestDto.java
  be/src/main/java/com/sharetravel/domain/travel/dto/TravelResponseDto.java
  be/src/main/java/com/sharetravel/domain/travel/dto/TravelSearchResponseDto.java
  be/src/main/java/com/sharetravel/domain/travel/entity/Travel.java
  be/src/main/java/com/sharetravel/domain/travel/repository/TravelRepository.java
  be/src/main/java/com/sharetravel/domain/travel/service/TravelService.java
  be/src/main/java/com/sharetravel/domain/travelreview/entity/TravelReview.java
  be/src/main/java/com/sharetravel/domain/user/dto/UserResponseDto.java
  be/src/main/java/com/sharetravel/domain/user/service/UserService.java
  be/src/main/java/com/sharetravel/global/api/ApiResponseCode.java
  be/src/main/java/com/sharetravel/global/auth/jwt/filter/JwtAuthenticationFilter.java
  be/src/main/resources/application.yml
  be/src/main/resources/schema.sql
  fe/public/marker.png
  fe/public/search_icon.png
  fe/src/api/index.js
  fe/src/api/travel.js
  fe/src/views/ShareTravelPage.vue
Labels: 👨‍💻 feature, 👨‍💻 backend, 👨‍💻 frontend

#41 [Feature/board] 게시판 백엔드 CRUD 기능 구현
  be/src/main/java/com/sharetravel/domain/board/controller/BoardController.java
  be/src/main/java/com/sharetravel/domain/board/dto/BoardDto.java
  be/src/main/java/com/sharetravel/domain/board/dto/BoardResponseDto.java
  be/src/main/java/com/sharetravel/domain/board/dto/BoardSaveRequestDto.java
  be/src/main/java/com/sharetravel/domain/board/dto/BoardSearchCondition.java
  be/src/main/java/com/sharetravel/domain/board/dto/BoardUpdateRequestDto.java
  be/src/main/java/com/sharetravel/domain/board/entity/Board.java
  be/src/main/java/com/sharetravel/domain/board/repository/BoardRepository.java
  be/src/main/java/com/sharetravel/domain/board/service/BoardService.java
  be/src/main/java/com/sharetravel/domain/boardCategory/controller/BoardCategoryController.java
  be/src/main/java/com/sharetravel/domain/boardCategory/dto/BoardCategoryDto.java
  be/src/main/java/com/sharetravel/domain/boardCategory/entity/BoardCategory.java
  be/src/main/java/com/sharetravel/domain/boardCategory/repository/BoardCategoryRepository.java
  be/src/main/java/com/sharetravel/domain/boardCategory/sevice/BoardCategoryService.java
  be/src/main/java/com/sharetravel/domain/boardcategory/controller/BoardCategoryController.java
  be/src/main/java/com/sharetravel/domain/boardcategory/entity/BoardCategory.java
  be/src/main/java/com/sharetravel/domain/boardcategory/repository/BoardCategoryRepository.java
  be/src/main/java/com/sharetravel/domain/boardcategory/sevice/BoardCategoryService.java
  be/src/main/java/com/sharetravel/domain/user/entity/User.java
  be/src/main/java/com/sharetravel/global/api/ApiResponseCode.java
  be/src/main/java/com/sharetravel/global/auth/jwt/filter/JwtAuthenticationFilter.java
  be/src/main/resources/schema.sql
Labels: 👨‍💻 feature, 👨‍💻 backend

#42 [infra] Vue.js 웹 앱 AWS 자동 배포 환경 구축
  .github/workflows/cicd-fe.yml
  .github/workflows/manual-deploy-fe.yml
Labels: 🖥 infra, 👨‍💻 frontend

#44 [Feature/travel] 여행지 정보 조회 기능 개선
  be/src/main/java/com/sharetravel/domain/travel/controller/TravelController.java
  be/src/main/java/com/sharetravel/domain/travel/dto/TravelResponseDto.java
  be/src/main/java/com/sharetravel/domain/travel/dto/TravelSearchResponseDto.java
  be/src/main/java/com/sharetravel/domain/travel/entity/Travel.java
  be/src/main/java/com/sharetravel/domain/travel/repository/TravelRepository.java
  be/src/main/java/com/sharetravel/domain/travel/service/TravelService.java
  be/src/main/resources/data.sql
  be/src/main/resources/schema.sql
  fe/public/arrow.png
  fe/public/travel/exercise.png
  fe/public/travel/nightview.png
  fe/public/travel/sense.png
  fe/public/travel/sunin.png
  fe/public/travel/sunout.png
  fe/public/travel/walking.png
  fe/src/api/travel.js
  fe/src/components/travel/TravelSearchBar.vue
  fe/src/components/user/LoginModal.vue
  fe/src/components/user/mypage/UserNavigation.vue
  fe/src/views/ShareTravelPage.vue
Labels: 👨‍💻 feature, 👨‍💻 backend, 👨‍💻 frontend

#45 [hotfix] fe cicd workflow 파일 오탈자 수정
  .github/workflows/cicd-fe.yml
  .github/workflows/manual-deploy-fe.yml
Labels: 🔧 hot fix, 🖥 infra

#46 [hotfix] 뷰 웹 앱 cicd workflow 오탈자 수정
  .github/workflows/cicd-fe.yml
Labels: 🔧 hot fix, 🖥 infra

#47 [hotfix] cicd workflow 파일 오탈자 재수정
  .github/workflows/manual-deploy-fe.yml
Labels: 🔧 hot fix, 🖥 infra

#49 [infra] 배포용 환경 변수 추가
  fe/.env.production
  fe/.gitignore
Labels: 🖥 infra

#48 [Be/feature/travel] 여행지 키워드 조회 시 데이터 캐싱 처리
  be/build.gradle
  be/src/main/java/com/sharetravel/ServerApplication.java
  be/src/main/java/com/sharetravel/domain/board/entity/Board.java
  be/src/main/java/com/sharetravel/domain/travelkeyword/dto/TravelKeywordResponseDto.java
  be/src/main/java/com/sharetravel/domain/travelkeyword/service/TravelKeywordService.java
  be/src/main/java/com/sharetravel/global/auth/oauth2/handler/CustomAuthenticationSuccessHandler.java
Labels: 👨‍💻 feature, 👨‍💻 backend

#50 [Fe/feature/board] 게시판 프론트 구현 / 헤더 및 푸터 수정
  .github/workflows/cicd-fe.yml
  be/src/main/java/com/sharetravel/domain/board/controller/BoardController.java
  be/src/main/java/com/sharetravel/domain/board/dto/BoardResponseDto.java
  be/src/main/java/com/sharetravel/domain/board/dto/BoardSaveRequestDto.java
  be/src/main/java/com/sharetravel/domain/board/entity/Board.java
  be/src/main/java/com/sharetravel/domain/board/repository/BoardRepository.java
  be/src/main/java/com/sharetravel/domain/boardcategory/entity/BoardCategory.java
  be/src/main/resources/schema.sql
  fe/src/App.vue
  fe/src/api/board.js
  fe/src/components/board/BoardModify.vue
  fe/src/components/board/BoardWrite.vue
  fe/src/components/board/content/BoardDetail.vue
  fe/src/components/board/content/BoardEvent.vue
  fe/src/components/board/content/BoardGeneralForum.vue
  fe/src/components/board/content/BoardNotice.vue
  fe/src/components/board/content/BoardTipForum.vue
  fe/src/components/common/AppFooter.vue
  fe/src/components/common/AppHeader.vue
  fe/src/store/index.js
  fe/src/views/BoardPage.vue
Labels: 👨‍💻 feature, 👨‍💻 frontend

#51 [hotfix] : refresh token SameSite 속성 Strict 설정
  be/src/main/java/com/sharetravel/domain/board/dto/BoardResponseDto.java
  be/src/main/java/com/sharetravel/domain/board/entity/Board.java
  be/src/main/java/com/sharetravel/global/auth/jwt/utils/TokenUtils.java
Labels: 🔧 hot fix, 👨‍💻 backend

#52 [hotfix] : Vue.js 환경변수 값 수정
  fe/.env.production
Labels: 🔧 hot fix, 🖥 infra, 👨‍💻 frontend

#53 [debug] 배포 시 발생하는 에러 디버깅 위한 코드 작성
  be/src/main/java/com/sharetravel/global/auth/jwt/controller/TokenController.java
  be/src/main/java/com/sharetravel/global/auth/jwt/filter/JwtAuthenticationFilter.java
  fe/.env.production
Labels: 🎃 bug

#54 [Refactor/auth] OAuth2 관련 불필요한 로직 삭제
  .github/workflows/cicd-be.yml
  .github/workflows/cicd-fe.yml
  be/src/main/java/com/sharetravel/global/auth/oauth2/dto/GoogleOAuth2UserInfo.java
  be/src/main/java/com/sharetravel/global/auth/oauth2/dto/KakaoOAuth2UserInfo.java
  be/src/main/java/com/sharetravel/global/auth/oauth2/dto/NaverOAuth2UserInfo.java
  be/src/main/java/com/sharetravel/global/auth/oauth2/dto/OAuth2UserInfo.java
  be/src/main/java/com/sharetravel/global/auth/oauth2/handler/CustomAuthenticationSuccessHandler.java
  be/src/main/java/com/sharetravel/global/auth/oauth2/utils/OAuth2UserInfoUtil.java
Labels: ♻ refactor

#55 [Be/refactor/user] 사용자 선호 여행지 키워드 삭제 시 delete batch 처리
  be/src/main/java/com/sharetravel/domain/user/entity/User.java
  be/src/main/java/com/sharetravel/domain/user/repository/UserRepository.java
  be/src/main/java/com/sharetravel/domain/user/repository/UserTravelKeywordRepository.java
  be/src/main/java/com/sharetravel/domain/user/service/UserService.java
  be/src/main/java/com/sharetravel/global/config/RedisConfig.java
Labels: 👨‍💻 feature, 👨‍💻 backend

#56 [Be/cicd/test] : 백엔드 CI/CD 이벤트 트리거 테스트
  be/build.gradle
Labels: 🖥 infra, 🛠 test
